### ISSUE TITLE
Can't load PDF URLs

### ISSUE THREAD

**Issue by daveliepmann** [dotemacs/pdfboxing#18]
Though PDFBox's `PDDocument/load` can handle PDFs given as a URL, pdfboxing cannot. This is because `load-pdf` wraps `PDDocument/load` with `is-pdf?`, which in turn relies on FileDataSource. [Joshua Miller delineates an approach](http://increasinglyfunctional.com/2013/12/05/parsing-pdfs-in-clojure/) that has no such restriction:

```
  (with-open [pd (PDDocument/load (URL. url))]
    (let [stripper (PDFTextStripper.)]
    (.getText stripper pd)))
```

I'm not sure how you want to approach this restriction so I don't have a PR at this time. Cheers!

**Comment by dotemacs** [comment]
Thanks for opening the issue to discuss this @daveliepmann  :)

I'm not emotionally attached to the current approach so I'd be open to adding this feature. 

A good approach would be to figure how to test this first.

**Comment by batasrki** [comment]
Actually, with version 2 of PDFBox, that approach doesn't work anymore.

`PDDocument/load` now takes, among others, an `InputStream`, meaning that the code has to be converted to:

```clojure
  (with-open [inputstream (-> (java.net.URL. url)
                              .openConnection
                              .getContent)
              pd (PDDocument/load inputstream)]
    (let [stripper (PDFTextStripper.)]
      (.getText stripper pd)))
```

**Comment by dotemacs** [comment]
Since PDFBox 2 doesn't have this feature and since I also feel that this library should concentrate only on it's core functionality, dealing with PDF manipulation, I'll retire this issue.

Thanks
