### ISSUE TITLE
warning on PDF merge

### ISSUE THREAD

**Issue by paultopia** [dotemacs/pdfboxing#25]
Hi there,

I've been messing around a little with this library, and I noticed that PDFBox generates a warning about not closing the file when using the merge example you give on the readme: 

```
Apr 02, 2016 12:30:17 PM org.apache.pdfbox.cos.COSDocument finalize
WARNING: Warning: You did not close a PDF Document
```

Is this expected behavior?  I'm not sure how PDFBox works under the hood, so not clear if this is a problem or just a silly warning that should be suppressed.  (When working with large collections of documents, does this perhaps suggest that it they won't be garbage collected?)

**Comment by dotemacs** [comment]
Hello @paultopia 

thank you for reporting this. 

Looking at this: 

https://github.com/apache/pdfbox/blob/85399e4ec004a8ec1a18f5f05a8dc0149300ec37/pdfbox/src/main/java/org/apache/pdfbox/cos/COSDocument.java#L468-L485

It seems that the warning is issued, but the document is closed right after. So I'd say that it's safe to use it as is now, but it would be good to clean it up and close the document explicitly.

I'll look into fixing this soon.

Thanks again

**Comment by paultopia** [comment]
cool, thanks!

**Comment by dotemacs** [comment]
Hello @paultopia 

This issue has been fixed with this commit: https://github.com/dotemacs/pdfboxing/commit/2ed58248360788cbdd4a4b5dbc95eadaddd9c767
I was just slow to update this issue.

I'll close this issue for now, but if it comes up for you again, for whatever reason, please let me know.
Thanks
