### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ilyabe** [dotemacs/pdfboxing#32]
I have a PDF file with a form field that's an image. Is there anything in this library to put an image in that field?

**Comment by dotemacs** [comment]
Hi @ilyabe 

apologies for not answering this sooner.

For dealing with the form fields there's this functionality:

https://github.com/dotemacs/pdfboxing#fill-in-pdf-forms

I've mostly dealt with form fields that handle text or are radio buttons/check boxes. Never really needed to add images to form fields. 

Have a look at this [thread on StackOverflow](http://stackoverflow.com/questions/32499129/is-there-any-field-to-hold-an-image-in-pdfbox-1-8-10) which talks about the possibility of doing this in PDFbox.

Hope that helps

**Comment by dotemacs** [comment]
I'll close this for now
