### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by nukecoder** [dotemacs/pdfboxing#4]
inof/page-numbers should be info/page-number

**Comment by dotemacs** [comment]
Hi @nukecoder,

where exactly do you see that typo? I can't find it. 

Thanks

**Comment by nukecoder** [comment]
It's this line: "(info/page-numbers "test/pdfs/interactiveform.pdf")"

I tried using the get page-numbers function, but it couldn't be found. A
quick look at your source code revealed that the function name is:
"(defn page-number".
So, the README has an s on the end of page-numbers, but your source is
page-number. That is the typo I was referring to.

**Comment by dotemacs** [comment]
Ah, I see. Good catch!

I know that the change is minor, but do you want to create a pull request for it, just so that the credit for it can stay in the code (via git logs)?

Thanks :smile:

**Comment by nukecoder** [comment]
I'm new to git, and I am not concerned with credit. I just want to help out
and thank you for writing PDFBoxing!

Thanks,
Wes
