### ISSUE TITLE
How to embed a signature of an image of a signature?

### ISSUE THREAD

**Issue by theronic** [dotemacs/pdfboxing#47]
I need to fill some PDF forms and render a signature on top of the form. Is this possible?

**Comment by dotemacs** [comment]
I don't think that I've enabled/abstracted every possible use of PDFBox with this library.

You're better off at looking how https://pdfbox.apache.org/ does it and then seeing if you can do the same but just by using Clojure. 99% that it's doable... Good luck

**Comment by theronic** [comment]
Thanks, I see I'll have to dive in there manually :)

Although I would recommend returning streams in your library and letting the user choose whether to save - I think many people just want to generate PDFs on-demand and not worry about storing them.

**Comment by dotemacs** [comment]
That's a good suggestion, thank you.

I'll try to get to it when I get some time.
