### ISSUE TITLE
Update to PDFBox 2.0.12 due to security issue in 2.0.11

### ISSUE THREAD

**Issue by cap10morgan** [dotemacs/pdfboxing#48]
Details are [here](https://pdfbox.apache.org)

**Comment by dotemacs** [comment]
Hey @cap10morgan 

thank you for raising this issue and my apologies for sleeping on it for so long.

I've now updated `pdfbox` to **2.0.16** as can be seen here: https://github.com/dotemacs/pdfboxing/commit/46c7c6808e3eaeb4d184e873b61724fae9a53b3b

I'll look to make a new release tomorrow.

Thanks again

**Comment by dotemacs** [comment]
I've released a new version with `pdfbox` **2.0.16**, available on Clojars now as `0.1.14`.

Thank you for your patience on this one and sorry I took so long.
