### ISSUE TITLE
Exception is thrown during lines drawing

### ISSUE THREAD

**Issue by pmensik** [dotemacs/pdfboxing#50]
`java.lang.IllegalArgumentException: No matching field found: getAllPages for class org.apache.pdfbox.pdmodel.PDDocumentCatalog` is raised when trying to draw a line. I will prepare PR for this simple fix :)

**Comment by dotemacs** [comment]
As explained in https://github.com/dotemacs/pdfboxing/pull/51, your changes that fix this are in the master
