### ISSUE TITLE
README wrongly documents split-pdf-at

### ISSUE THREAD

**Issue by werenall** [dotemacs/pdfboxing#54]
In readme we can read:
`Splits the PDF in half and writes them to disk as clojure-1.pdf and clojure-2.pdf`

The example below is code that truly splits its input file in half. But there's no way you specify what the output files are.

**Comment by dotemacs** [comment]
What do you propose? Thanks

**Comment by dotemacs** [comment]
What do you propose? Thanks

**Comment by werenall** [comment]
Hmm... a quick win would be to simply change the names in README:
`Splits the PDF in half and writes them to disk as multi-page-1.pdf and multi-page-2.pdf`
I personally don't think it's worth the effort to make this function more sophisticated. In fact, I would even deprecate it. Since `split-pdf` returns PDDocument for each page and `merge-pdfs` is capable of joining them however one can want, then this is just a sugar.

**Comment by dotemacs** [comment]
Ah, I see what you're saying, the description uses one file (clojure*pdf) name and the code sample uses a different one (multi-page*)... OK, that should be corrected.

**Comment by dotemacs** [comment]
Fixed with https://github.com/dotemacs/pdfboxing/commit/78f9e822a6463c84bb8f257c8bc5956bd8269258

Thanks for this and sorry for the delay
