### ISSUE TITLE
Less strict `merge-pdfs`

### ISSUE THREAD

**Issue by Akeboshiwind** [dotemacs/pdfboxing#66]
## Expected Behavior
I have a couple of `input-streams` containing PDFs that I want to merge into an `output-stream`.

The current `merge-pdfs` function requires that all [inputs are files](https://github.com/dotemacs/pdfboxing/blob/ac810b22aafc32412b6450ef6b7be251ffad53e0/src/pdfboxing/merge.clj#L40), but PDFBox supports [adding `InputStreams`](https://pdfbox.apache.org/docs/2.0.1/javadocs/org/apache/pdfbox/multipdf/PDFMergerUtility.html#addSource(java.io.InputStream)).

Same with the output, `merge-pdfs` requires that the [output is a filename](https://github.com/dotemacs/pdfboxing/blob/ac810b22aafc32412b6450ef6b7be251ffad53e0/src/pdfboxing/merge.clj#L41), but PDFBox supports both [filenames](https://pdfbox.apache.org/docs/2.0.1/javadocs/org/apache/pdfbox/multipdf/PDFMergerUtility.html#setDestinationFileName(java.lang.String)) and [`OutputStreams`](https://pdfbox.apache.org/docs/2.0.1/javadocs/org/apache/pdfbox/multipdf/PDFMergerUtility.html#setDestinationStream(java.io.OutputStream)).

## Potential Solution

To solve this in my codebase I've updated `merge-pdfs` to be less strict:
```clojure
(defn merge-pdfs [& {:keys [input output]}]
  (let [merger (PDFMergerUtility.)]
    (doseq [source input]
      (.addSource merger source))
    (cond
      (instance? java.io.OutputStream output)
      (.setDestinationStream merger output)

      :else
      (.setDestinationFileName merger output))
    (.mergeDocuments merger)))
```

But I wanted your feedback before submitting a PR.
Is this something you'd be interested in?

**Comment by dotemacs** [comment]
Hey @Akeboshiwind 

If you can get this to work **and also ensure that there are no broken tests**, I'd be happy to merge this in.

Thank you
