### ISSUE TITLE
Upgrade to pdfbox 3

### ISSUE THREAD

**Issue by raymcdermott** [dotemacs/pdfboxing#78]
## Expected Behavior
Update the code to align with the [major changes in pdfbox v3](https://pdfbox.apache.org/3.0/migration.html)

## Actual Behavior
Tests pass after upgrade

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:
- Subsystem:

## Anything else that you think is relevant
I have made the updates in [a fork](https://github.com/raymcdermott/pdfboxing)

Let me know if you will accept a PR

[ I ask because I see that there are several open PRs and I don't want to waste your time ]

**Comment by raymcdermott** [comment]
https://github.com/dotemacs/pdfboxing/pull/79

**Comment by dotemacs** [comment]
Done via #79
